const chat=document.getElementById('chat'),message=document.getElementById('message'),send=document.getElementById('send'),newChat=document.getElementById('newChat'),typing=document.getElementById('typing'),brainStage=document.getElementById('brainStage'),brainState=document.getElementById('brainState'),voice=document.getElementById('voice');
const GATEWAY='https://super-cerebro.hatchable.site/api/chat';
let recognition=null,history=[],selectedImage=null,tesseractPromise=null,sending=false;
let currentChatId=localStorage.getItem('super_cerebro_current_chat')||('chat-'+Date.now());
let currentChatTitle=localStorage.getItem('super_cerebro_current_title')||'Nova conversa';
const MEMORY_DB='super-cerebro-memory',MEMORY_STORE='messages',MEMORY_META='chats';
function memoryDB(){return new Promise((resolve,reject)=>{const r=indexedDB.open(MEMORY_DB,1);r.onupgradeneeded=()=>{const db=r.result;if(!db.objectStoreNames.contains(MEMORY_STORE)){const s=db.createObjectStore(MEMORY_STORE,{keyPath:'id',autoIncrement:true});s.createIndex('chatId','chatId')}if(!db.objectStoreNames.contains(MEMORY_META)){db.createObjectStore(MEMORY_META,{keyPath:'id'})}};r.onsuccess=()=>resolve(r.result);r.onerror=()=>reject(r.error)})}
async function memoryPutMessage(role,text){try{const db=await memoryDB();await new Promise((res,rej)=>{const tx=db.transaction(MEMORY_STORE,'readwrite');tx.objectStore(MEMORY_STORE).add({chatId:currentChatId,role,text:String(text||''),createdAt:Date.now()});tx.oncomplete=res;tx.onerror=()=>rej(tx.error)});await memoryTouchChat(text)}catch(e){console.warn('Memória local:',e)}}
async function memoryTouchChat(firstText){try{const db=await memoryDB();const title=currentChatTitle==='Nova conversa'&&firstText?String(firstText).replace(/\s+/g,' ').trim().slice(0,54):currentChatTitle;currentChatTitle=title||'Nova conversa';localStorage.setItem('super_cerebro_current_chat',currentChatId);localStorage.setItem('super_cerebro_current_title',currentChatTitle);await new Promise((res,rej)=>{const tx=db.transaction(MEMORY_META,'readwrite');tx.objectStore(MEMORY_META).put({id:currentChatId,title:currentChatTitle,updatedAt:Date.now()});tx.oncomplete=res;tx.onerror=()=>rej(tx.error)})}catch(e){console.warn('Metadados da memória:',e)}}
async function memoryList(){const db=await memoryDB();return new Promise((res,rej)=>{const tx=db.transaction([MEMORY_META,MEMORY_STORE],'readonly');const chats=tx.objectStore(MEMORY_META).getAll();const msgs=tx.objectStore(MEMORY_STORE).getAll();tx.oncomplete=()=>{const counts={};for(const m of msgs.result)counts[m.chatId]=(counts[m.chatId]||0)+1;res(chats.result.filter(x=>counts[x.id]).sort((a,b)=>b.updatedAt-a.updatedAt).map(x=>({...x,count:counts[x.id]})))};tx.onerror=()=>rej(tx.error)})}
async function memoryLoad(id){const db=await memoryDB();return new Promise((res,rej)=>{const tx=db.transaction([MEMORY_META,MEMORY_STORE],'readonly');const meta=tx.objectStore(MEMORY_META).get(id);const all=tx.objectStore(MEMORY_STORE).index('chatId').getAll(IDBKeyRange.only(id));tx.oncomplete=()=>res({meta:meta.result,messages:all.result.sort((a,b)=>a.createdAt-b.createdAt)});tx.onerror=()=>rej(tx.error)})}
async function memoryDelete(id){const db=await memoryDB();await new Promise((res,rej)=>{const tx=db.transaction([MEMORY_META,MEMORY_STORE],'readwrite');tx.objectStore(MEMORY_META).delete(id);const idx=tx.objectStore(MEMORY_STORE).index('chatId');idx.openCursor(IDBKeyRange.only(id)).onsuccess=e=>{const cur=e.target.result;if(cur){cur.delete();cur.continue()}};tx.oncomplete=res;tx.onerror=()=>rej(tx.error)});if(id===currentChatId)newChatSession()}
function newChatSession(){currentChatId='chat-'+Date.now()+'-'+Math.random().toString(36).slice(2,7);currentChatTitle='Nova conversa';localStorage.setItem('super_cerebro_current_chat',currentChatId);localStorage.setItem('super_cerebro_current_title',currentChatTitle);history=[];location.reload()}
async function openMemory(){const panel=document.getElementById('memoryPanel'),list=document.getElementById('memoryList');if(!panel||!list)return;panel.classList.add('open');list.innerHTML='<div class="memory-empty">Carregando conversas...</div>';try{const chats=await memoryList();if(!chats.length){list.innerHTML='<div class="memory-empty">Nenhuma conversa salva ainda.</div>';return}list.innerHTML='';for(const x of chats){const b=document.createElement('button');b.className='memory-item';b.innerHTML='<strong></strong><span></span><i>›</i>';b.querySelector('strong').textContent=x.title;b.querySelector('span').textContent=new Date(x.updatedAt).toLocaleString('pt-BR')+' • '+x.count+' mensagens';b.onclick=()=>restoreMemory(x.id);list.appendChild(b)}}catch(e){list.innerHTML='<div class="memory-empty">Não foi possível abrir a memória local.</div>'}}
function closeMemory(){document.getElementById('memoryPanel')?.classList.remove('open')}
async function restoreMemory(id){try{const data=await memoryLoad(id);if(!data?.messages?.length)return;currentChatId=id;currentChatTitle=data.meta?.title||'Conversa';localStorage.setItem('super_cerebro_current_chat',id);localStorage.setItem('super_cerebro_current_title',currentChatTitle);history=[];chat.innerHTML='';document.body.classList.remove('chat-mode');for(const m of data.messages){history.push({role:m.role,content:m.text});addMessage(m.role,m.text,false)}if(history.length>30)history=history.slice(-30);closeMemory();requestAnimationFrame(()=>chat.scrollTop=chat.scrollHeight)}catch(e){console.error(e)}}
function cognitiveSystem(text){return window.SuperCerebroCognitive?.buildSystem(text)||'Você é o Super Cérebro. Responda em português do Brasil com precisão, raciocínio cuidadoso e sem inventar informações.'}
function setBrainState(s){brainStage.classList.remove('thinking','listening','speaking');if(s)brainStage.classList.add(s);brainState.textContent=({listening:'Ouvindo...',thinking:'Pensando...',speaking:'Falando...'}[s]||'Pronto para pensar')}
function enterChatMode(){document.body.classList.add('chat-mode');chat.classList.add('has-messages')}
function addMessage(role,text,persist=true){enterChatMode();if(persist)memoryPutMessage(role,text);const row=document.createElement('div');row.className=`message-row ${role}`;const box=document.createElement('div');box.className='bubble';const label=document.createElement('div');label.className='message-label';label.textContent=role==='user'?'Você':'Super Cérebro';const content=document.createElement('div');content.textContent=text;box.append(label,content);row.appendChild(box);chat.appendChild(row);requestAnimationFrame(()=>row.scrollIntoView({behavior:'smooth',block:'end'}))}
function setTyping(on){typing.innerHTML=on?'<span class="typing"><i></i><i></i><i></i></span>':''}
function cleanSpeechText(text){return String(text||'').replace(/\\([^)]*\\)/g,' ').replace(/\[[^\]]*\]/g,' ').replace(/\*+/g,' ').replace(/_+/g,' ').replace(/#{1,6}\s*/g,' ').replace(/^[>\-+]\s+/gm,' ').replace(/`+/g,' ').replace(/https?:\/\/\S+/g,' ').replace(/\s{2,}/g,' ').trim()}
let localTTS=null,localTTSLoading=null,ttsAudioContext=null,ttsSource=null;
const TTS_MODEL='onnx-community/Supertonic-TTS-2-ONNX';
const TTS_VOICE='https://huggingface.co/onnx-community/Supertonic-TTS-2-ONNX/resolve/main/voices/M1.bin';
async function loadLocalMaleTTS(){
  if(localTTS)return localTTS;
  if(localTTSLoading)return localTTSLoading;
  localTTSLoading=(async()=>{const mod=await import('https://cdn.jsdelivr.net/npm/@huggingface/transformers@4.3.0');let opts={dtype:'q8'};if('gpu' in navigator)opts.device='webgpu';try{localTTS=await mod.pipeline('text-to-speech',TTS_MODEL,opts)}catch(e){delete opts.device;localTTS=await mod.pipeline('text-to-speech',TTS_MODEL,opts)}return localTTS})();
  try{return await localTTSLoading}finally{localTTSLoading=null}
}
function prepareAudioContext(){if(!window.AudioContext&&!window.webkitAudioContext)throw new Error('Este navegador não oferece Web Audio.');if(!ttsAudioContext)ttsAudioContext=new(window.AudioContext||window.webkitAudioContext)();if(ttsAudioContext.state==='suspended')ttsAudioContext.resume().catch(()=>{});return ttsAudioContext}
function primeAudio(){try{const ctx=prepareAudioContext();if(ctx.state==='suspended')ctx.resume();const b=ctx.createBuffer(1,1,44100);const s=ctx.createBufferSource();s.buffer=b;s.connect(ctx.destination);s.start()}catch(e){console.warn('Preparação do áudio:',e)}}
async function playLocalAudio(output){const data=output?.audio;if(!data)throw new Error('Supertonic não retornou amostras de áudio.');const samples=data instanceof Float32Array?data:new Float32Array(data);const rate=output?.sampling_rate||44100;const ctx=prepareAudioContext();await ctx.resume();if(ttsSource){try{ttsSource.stop()}catch{}}const buffer=ctx.createBuffer(1,samples.length,rate);buffer.copyToChannel(samples,0);ttsSource=ctx.createBufferSource();ttsSource.buffer=buffer;ttsSource.connect(ctx.destination);await new Promise((resolve,reject)=>{const src=ttsSource;src.onended=()=>resolve();try{src.start(0)}catch(e){reject(e)}})}
function splitSpeech(text){const parts=String(text||'').match(/[^.!?;:]+[.!?;:]*(?:\\s+|$)/g)||[text];const out=[];let acc='';for(const p of parts){if((acc+' '+p).trim().length>360&&acc){out.push(acc.trim());acc=p}else acc+=' '+p}if(acc.trim())out.push(acc.trim());return out.filter(Boolean)}
async function speakAnswer(text){const clean=cleanSpeechText(text);if(!clean)return;setBrainState('speaking');try{const tts=await loadLocalMaleTTS();for(const part of splitSpeech(clean)){const output=await tts('<pt>'+part+'</pt>',{speaker_embeddings:TTS_VOICE,num_inference_steps:5,speed:1.0});await playLocalAudio(output)}setBrainState('')}catch(e){console.error('TTS local:',e);setBrainState('');try{await speakAndroidFallback(clean)}catch(f){showVoiceError('A voz masculina local falhou. Toque em 🔊 para ver o diagnóstico.')}}}
function getAvailableVoices(){try{return 'speechSynthesis' in window?speechSynthesis.getVoices():[]}catch{return[]}}
function pickMalePortugueseVoice(){
  const voices=getAvailableVoices();
  const pt=voices.filter(v=>/^pt-BR$/i.test(v.lang)||/^pt-BR-/i.test(v.lang)||/^pt_/i.test(v.lang));
  const maleNames=/antonio|ricardo|daniel|felipe|luciano|rafael|thiago|tiago|jo[aã]o|guilherme|paulo|carlos|bruno|marcelo|eduardo|mateus|pedro|lucas|andre|andré|male|mascul|homem/i;
  return pt.find(v=>maleNames.test(v.name))||null;
}
function pickPortugueseVoice(){
  const voices=getAvailableVoices();
  return voices.find(v=>/^pt-BR$/i.test(v.lang))||voices.find(v=>/^pt-BR-/i.test(v.lang))||voices.find(v=>/^pt/i.test(v.lang))||null;
}
function voiceDiagnostics(){
  const voices=getAvailableVoices();
  return {speechSynthesis:'speechSynthesis' in window,audioContext:!!(window.AudioContext||window.webkitAudioContext),voices:voices.map(v=>({name:v.name,lang:v.lang,local:!!v.localService,default:!!v.default})),malePortuguese:pickMalePortugueseVoice()?.name||null,portuguese:pickPortugueseVoice()?.name||null};
}
function speakWithDeviceMaleVoice(text){
  return new Promise((resolve,reject)=>{
    if(!('speechSynthesis' in window)){reject(new Error('O navegador não oferece síntese de voz.'));return}
    const synth=speechSynthesis;
    let finished=false;
    const voicesReady=()=>{
      const male=pickMalePortugueseVoice();
      const pt=pickPortugueseVoice();
      const chosen=male||pt;
      if(!chosen){reject(new Error('Nenhuma voz em português foi disponibilizada pelo Android/navegador.'));return}
      synth.cancel();
      try{synth.resume()}catch{}
      const u=new SpeechSynthesisUtterance(cleanSpeechText(text));
      u.lang=chosen.lang||'pt-BR';
      u.voice=chosen;
      u.rate=.94;
      u.pitch=male?.name?.match(/male|mascul|homem/i)?.[0] ? .88 : .72;
      u.volume=1;
      u.onstart=()=>{setBrainState('speaking');showVoiceError('Voz: '+chosen.name+' • '+chosen.lang)};
      u.onend=()=>{if(!finished){finished=true;setBrainState('');resolve(chosen.name)}};
      u.onerror=e=>{if(!finished){finished=true;setBrainState('');reject(new Error(e?.error||'Falha na síntese de voz'))}};
      synth.speak(u);
      setTimeout(()=>{if(!finished&&!synth.speaking&&!synth.pending){try{synth.resume();synth.speak(u)}catch{}}},700);
    };
    const voices=getAvailableVoices();
    if(voices.length)voicesReady();else{
      let done=false;
      const once=()=>{if(done)return;done=true;synth.removeEventListener?.('voiceschanged',once);voicesReady()};
      synth.addEventListener?.('voiceschanged',once);
      setTimeout(()=>{if(!done){done=true;synth.removeEventListener?.('voiceschanged',once);voicesReady()}},1500);
    }
  });
}
async function speakAnswer(text){
  const clean=cleanSpeechText(text);
  if(!clean)return;
  try{await speakWithDeviceMaleVoice(clean);return}catch(e){console.warn('Voz do dispositivo:',e)}
  setBrainState('speaking');
  try{const tts=await loadLocalMaleTTS();for(const part of splitSpeech(clean)){const output=await tts('<pt>'+part+'</pt>',{speaker_embeddings:TTS_VOICE,num_inference_steps:5,speed:1.0});await playLocalAudio(output)}setBrainState('')}catch(e){setBrainState('');showVoiceError('Voz indisponível: '+(e?.message||'erro desconhecido'))}
}
async function testMaleVoice(){
  primeAudio();
  const text='Olá. Eu sou o Super Cérebro. Minha voz é masculina e estou funcionando.';
  try{const name=await speakWithDeviceMaleVoice(text);showVoiceError('Teste OK • '+name);return}
  catch(e){console.warn('Voz do dispositivo falhou:',e)}
  try{setBrainState('speaking');const tts=await loadLocalMaleTTS();const output=await tts('<pt>'+text+'</pt>',{speaker_embeddings:TTS_VOICE,num_inference_steps:5,speed:1.0});await playLocalAudio(output);setBrainState('');showVoiceError('Teste OK • Supertonic M1')}catch(e){setBrainState('');const d=voiceDiagnostics();const names=d.voices.slice(0,8).map(v=>v.name+' ('+v.lang+')').join(' | ');showVoiceError('Nenhuma voz masculina pt-BR disponível. Vozes encontradas: '+(names||'nenhuma'));console.error('Diagnóstico de voz:',d,e)}}
function showVoiceError(t){const el=document.getElementById('voiceStatus');if(el){el.textContent=t;el.classList.add('show');clearTimeout(showVoiceError.t);showVoiceError.t=setTimeout(()=>el.classList.remove('show'),9000)}}
function getVoiceDebug(){return voiceDiagnostics()}
async function callVireonix(value,extraContext=''){const userText=extraContext?`${value}\n\n${extraContext}`:value;const messages=[{role:'system',content:cognitiveSystem(userText)},...history,{role:'user',content:userText}];let lastError='Falha de conexão com o Vireonix.';for(let attempt=0;attempt<3;attempt++){try{const controller=new AbortController();const timer=setTimeout(()=>controller.abort(),60000);let r;try{r=await fetch(GATEWAY,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({model:'auto',messages}),signal:controller.signal,cache:'no-store'})}finally{clearTimeout(timer)}const raw=await r.text();let d={};try{d=raw?JSON.parse(raw):{}}catch{}if(!r.ok){lastError=`Gateway HTTP ${r.status}: ${d?.error?.message||d?.error?.type||raw||'erro'}`;if((r.status===429||r.status>=500)&&attempt<2){await new Promise(x=>setTimeout(x,1200*(attempt+1)));continue}throw new Error(lastError)}const answer=d?.choices?.[0]?.message?.content||d?.content||d?.result;if(typeof answer!=='string'||!answer.trim())throw new Error('O Vireonix respondeu sem conteúdo.');return answer.trim()}catch(e){lastError=e?.name==='AbortError'?'A conexão demorou mais de 60 segundos para responder.':e?.message||lastError;if(attempt<2)await new Promise(x=>setTimeout(x,1200*(attempt+1)))}}throw new Error(lastError)}
function loadTesseract(){if(window.Tesseract)return Promise.resolve(window.Tesseract);if(tesseractPromise)return tesseractPromise;tesseractPromise=new Promise((resolve,reject)=>{const s=document.createElement('script');s.src='https://cdn.jsdelivr.net/npm/tesseract.js@5/dist/tesseract.min.js';s.async=true;s.onload=()=>window.Tesseract?resolve(window.Tesseract):reject(new Error('O leitor OCR não carregou.'));s.onerror=()=>reject(new Error('Não foi possível carregar o leitor OCR. Verifique a conexão e tente novamente.'));document.head.appendChild(s)});return tesseractPromise}
async function prepareImage(file){const bitmap=await createImageBitmap(file);const max=2400,scale=Math.min(1,max/Math.max(bitmap.width,bitmap.height));const canvas=document.createElement('canvas');canvas.width=Math.max(1,Math.round(bitmap.width*scale));canvas.height=Math.max(1,Math.round(bitmap.height*scale));const ctx=canvas.getContext('2d',{willReadFrequently:true});ctx.drawImage(bitmap,0,0,canvas.width,canvas.height);bitmap.close();const img=ctx.getImageData(0,0,canvas.width,canvas.height),d=img.data;for(let i=0;i<d.length;i+=4){const y=.299*d[i]+.587*d[i+1]+.114*d[i+2];const v=y<150?Math.max(0,y-12):Math.min(255,y+10);d[i]=d[i+1]=d[i+2]=v}ctx.putImageData(img,0,0);return canvas}
async function readImageText(file){const T=await loadTesseract();setBrainState('thinking');brainState.textContent='Preparando leitura do print...';let source=file;try{source=await prepareImage(file)}catch{}const result=await T.recognize(source,'por+eng',{logger:m=>{if(m.status==='loading language data')brainState.textContent='Carregando idioma do leitor...';else if(m.status==='recognizing text'&&typeof m.progress==='number')brainState.textContent=`Lendo imagem... ${Math.round(m.progress*100)}%`}});return(result?.data?.text||'').replace(/[ \t]+\n/g,'\n').replace(/\n{3,}/g,'\n\n').trim()}
async function ask(text){const value=text.trim(),hasImage=!!selectedImage;if((!value&&!hasImage)||sending)return;document.getElementById('welcome')?.remove();const imageForRead=selectedImage,imageName=imageForRead?.name||'print';addMessage('user',hasImage?`🖼️ ${imageName}${value?'\n'+value:''}`:value);message.value='';message.style.height='48px';sending=true;setTyping(true);setBrainState('thinking');try{let context='';if(imageForRead){let ocr='';let ocrError='';try{ocr=await readImageText(imageForRead)}catch(e){ocrError=e?.message||'falha desconhecida'}context=`ATENÇÃO: O usuário enviou um print/imagem. Você NÃO deve responder que não consegue visualizar imagens. A imagem foi processada localmente por OCR e o texto extraído está abaixo. Responda usando esse texto como a fonte do conteúdo visível. Explique em português do Brasil, com detalhes e sem inventar. Identifique títulos, mensagens, avisos, números, datas, nomes, botões, campos, erros e instruções. Preserve valores e palavras importantes. Se algum trecho estiver incompleto ou estranho, marque como [trecho possivelmente incorreto] e explique o que ainda dá para concluir. Se o usuário não fez uma pergunta específica, primeiro diga claramente o que o print mostra e depois explique cada parte.\n\nNOME DO ARQUIVO: ${imageName}\n\nTEXTO EXTRAÍDO DO PRINT:\n${ocr||'[OCR não conseguiu extrair texto desta imagem. Não diga que você não pode visualizar imagens; informe apenas que a leitura automática falhou e peça um print mais nítido ou com maior resolução.]'}${ocrError?'\n\nDETALHE TÉCNICO DO OCR (não precisa mostrar ao usuário): '+ocrError:''}`}const answer=await callVireonix(value||'Leia e explique este print detalhadamente.',context);history.push({role:'user',content:context?`${value||'Leia e explique este print detalhadamente.'}\n${context}`:value},{role:'assistant',content:answer});if(history.length>30)history=history.slice(-30);addMessage('assistant',answer);speakAnswer(answer).catch(()=>{}); }catch(e){addMessage('assistant',`Não consegui processar a imagem ou conectar ao Vireonix.\n\n${e.message}`);setBrainState('')}finally{selectedImage=null;const f=document.getElementById('fileInput');if(f)f.value='';document.getElementById('attachmentPreview')?.classList.remove('show');const info=document.getElementById('attachmentInfo');if(info)info.textContent='';setTyping(false);sending=false;send.disabled=false;send.style.visibility='visible';send.style.opacity='1';message.focus()}}
function startVoice(){const R=window.SpeechRecognition||window.webkitSpeechRecognition;if(!R){addMessage('assistant','Seu navegador não oferece reconhecimento de voz.');return}recognition?.abort();recognition=new R();recognition.lang='pt-BR';recognition.interimResults=true;recognition.continuous=false;voice.classList.add('active');setBrainState('listening');recognition.onresult=e=>{let t='';for(let i=e.resultIndex;i<e.results.length;i++)t+=e.results[i][0].transcript;message.value=t;message.dispatchEvent(new Event('input'))};recognition.onend=()=>{voice.classList.remove('active');if(message.value.trim())ask(message.value);else setBrainState('')};recognition.onerror=()=>{voice.classList.remove('active');setBrainState('')};recognition.start()}
const fileInput=document.getElementById('fileInput');document.addEventListener('change',e=>{if(e.target!==fileInput)return;const f=e.target.files?.[0];if(!f)return;if(!f.type.startsWith('image/')){alert('Escolha uma imagem ou print.');e.target.value='';return}selectedImage=f;const info=document.getElementById('attachmentInfo'),preview=document.getElementById('attachmentPreview');if(info)info.textContent=`🖼️ ${f.name} • ${Math.round(f.size/1024)} KB • pronto para leitura`;preview?.classList.add('show')},true);document.getElementById('removeAttachment')?.addEventListener('click',()=>{selectedImage=null;if(fileInput)fileInput.value='';document.getElementById('attachmentPreview')?.classList.remove('show')});send.onclick=()=>{primeAudio();ask(message.value)};voice.onclick=()=>{primeAudio();startVoice()};message.oninput=()=>{message.style.height='48px';message.style.height=`${Math.min(message.scrollHeight,180)}px`};message.onkeydown=e=>{if(e.key==='Enter'&&!e.shiftKey){e.preventDefault();ask(message.value)}};document.querySelectorAll('[data-prompt]').forEach(b=>b.onclick=()=>ask(b.dataset.prompt||''));newChat.onclick=()=>{newChatSession()};
window.getVoiceDebug=getVoiceDebug;
window.clearSelectedImage=()=>{selectedImage=null;const f=document.getElementById('fileInput');if(f)f.value='';document.getElementById('attachmentPreview')?.classList.remove('show');const info=document.getElementById('attachmentInfo');if(info)info.textContent=''};
window.openMemory=openMemory;
window.testMaleVoice=testMaleVoice;