const chat=document.getElementById('chat'),message=document.getElementById('message'),send=document.getElementById('send'),newChat=document.getElementById('newChat'),typing=document.getElementById('typing'),brainStage=document.getElementById('brainStage'),brainState=document.getElementById('brainState'),voice=document.getElementById('voice'),canvas=document.getElementById('brainCanvas'),ctx=canvas.getContext('2d');
const VIREONIX='https://vireonix.ai/v1/chat/completions';const LOCAL_API='/api/chat';let recognition=null,audioContext=null,analyser=null,micStream=null,micData=null,voiceLevel=0,history=[],pulse=0;
function setBrainState(s){brainStage.classList.remove('thinking','listening','speaking');if(s)brainStage.classList.add(s);brainState.textContent=({listening:'Ouvindo...',thinking:'Pensando...',speaking:'Falando...'}[s]||'Pronto para pensar')}
function enterChatMode(){document.body.classList.add('chat-mode');chat.classList.add('has-messages')}
function addMessage(role,text){enterChatMode();const row=document.createElement('div');row.className=`message-row ${role}`;const box=document.createElement('div');box.className='bubble';const label=document.createElement('div');label.className='message-label';label.textContent=role==='user'?'Você':'Super Cérebro';const content=document.createElement('div');content.textContent=text;box.append(label,content);row.appendChild(box);chat.appendChild(row);requestAnimationFrame(()=>row.scrollIntoView({behavior:'smooth',block:'end'}))}
function setTyping(on){typing.innerHTML=on?'<span class="typing"><i></i><i></i><i></i></span>':''}
function speakAnswer(text){if(!('speechSynthesis'in window))return;window.speechSynthesis.cancel();const u=new SpeechSynthesisUtterance(text);u.lang='pt-BR';u.rate=.98;u.pitch=.95;u.onstart=()=>setBrainState('speaking');u.onend=()=>setBrainState('');u.onerror=()=>setBrainState('');window.speechSynthesis.speak(u)}
async function fetchWithTimeout(url,options,ms=30000){const controller=new AbortController(),timer=setTimeout(()=>controller.abort(),ms);try{return await fetch(url,{...options,signal:controller.signal})}finally{clearTimeout(timer)}}
async function callLocal(value){const r=await fetchWithTimeout(LOCAL_API,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({message:value})},120000);const d=await r.json().catch(()=>({}));if(!r.ok)throw new Error(d?.error||`Servidor HTTP ${r.status}`);if(!d.answer)throw new Error('Servidor não retornou resposta.');return d.answer}
async function callVireonix(value){const body={model:'auto',messages:[{role:'system',content:'Você é o Super Cérebro. Responda em português do Brasil. Raciocine com cuidado, não invente fatos, seja útil e direto. Vireonix é o único cérebro do sistema.'},...history,{role:'user',content:value}]};const r=await fetchWithTimeout(VIREONIX,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)},30000);const d=await r.json().catch(()=>({}));if(!r.ok)throw new Error(d?.error?.message||d?.error||`Vireonix HTTP ${r.status}`);const answer=d?.choices?.[0]?.message?.content;if(!answer)throw new Error('O Vireonix não retornou conteúdo.');return answer}
async function callBrain(value){let localError=null;try{return await callLocal(value)}catch(e){localError=e}try{return await callVireonix(value)}catch(e){if(localError)throw new Error(`Servidor: ${localError.message}\nVireonix: ${e.message}`);throw e}}
async function ask(text){const value=text.trim();if(!value||send.disabled)return;document.getElementById('welcome')?.remove();history.push({role:'user',content:value});if(history.length>20)history=history.slice(-20);addMessage('user',value);message.value='';message.style.height='48px';send.disabled=true;setTyping(true);setBrainState('thinking');pulse=1;try{const answer=await callBrain(value);history.push({role:'assistant',content:answer});if(history.length>20)history=history.slice(-20);addMessage('assistant',answer);speakAnswer(answer)}catch(e){setBrainState('');addMessage('assistant',`Não consegui obter resposta do Vireonix agora.\n\n${e.message}`)}finally{setTyping(false);send.disabled=false;message.focus()}}
async function startMicMonitor(){try{audioContext=new(window.AudioContext||window.webkitAudioContext)();micStream=await navigator.mediaDevices.getUserMedia({audio:true});const source=audioContext.createMediaStreamSource(micStream);analyser=audioContext.createAnalyser();analyser.fftSize=256;source.connect(analyser);micData=new Uint8Array(analyser.frequencyBinCount);monitorMic()}catch(e){}}
function monitorMic(){if(!analyser)return;analyser.getByteTimeDomainData(micData);let sum=0;for(const n of micData){const v=(n-128)/128;sum+=v*v}voiceLevel=Math.min(1,Math.sqrt(sum/micData.length)*4);requestAnimationFrame(monitorMic)}
function stopMicMonitor(){if(micStream)micStream.getTracks().forEach(t=>t.stop());micStream=null;if(audioContext)audioContext.close().catch(()=>{});audioContext=null;analyser=null;micData=null;voiceLevel=0}
function startVoice(){const R=window.SpeechRecognition||window.webkitSpeechRecognition;if(!R){addMessage('assistant','Seu navegador não oferece reconhecimento de voz.');return}recognition?.abort();recognition=new R();recognition.lang='pt-BR';recognition.interimResults=true;recognition.continuous=false;voice.classList.add('active');setBrainState('listening');startMicMonitor();recognition.onresult=e=>{let t='';for(let i=e.resultIndex;i<e.results.length;i++)t+=e.results[i][0].transcript;message.value=t;message.dispatchEvent(new Event('input'))};recognition.onend=()=>{voice.classList.remove('active');stopMicMonitor();if(message.value.trim())ask(message.value);else setBrainState('')};recognition.onerror=()=>{voice.classList.remove('active');stopMicMonitor();setBrainState('')};recognition.start()}
function resize(){const d=Math.min(devicePixelRatio||1,2),r=canvas.getBoundingClientRect();canvas.width=r.width*d;canvas.height=r.height*d;ctx.setTransform(d,0,0,d,0,0)}
function brainPath(cx,cy,rx,ry){ctx.beginPath();ctx.moveTo(cx,cy-ry);ctx.bezierCurveTo(cx-rx*.2,cy-ry*1.05,cx-rx*.75,cy-ry*.95,cx-rx*.9,cy-ry*.55);ctx.bezierCurveTo(cx-rx*1.08,cy-.05*ry,cx-rx*.92,cy+ry*.55,cx-rx*.55,cy+ry*.72);ctx.bezierCurveTo(cx-rx*.3,cy+ry*.9,cx-rx*.12,cy+ry*.72,cx,cy+ry*.82);ctx.bezierCurveTo(cx+rx*.12,cy+ry*.72,cx+rx*.3,cy+ry*.9,cx+rx*.55,cy+ry*.72);ctx.bezierCurveTo(cx+rx*.92,cy+ry*.55,cx+rx*1.08,cy-.05*ry,cx+rx*.9,cy-ry*.55);ctx.bezierCurveTo(cx+rx*.75,cy-ry*.95,cx+rx*.2,cy-ry*1.05,cx,cy-ry);ctx.closePath()}
function drawGyrus(cx,cy,rx,ry,side){const paths=[[-.58,-.48,-.2,-.18],[.02,-.57,.46,-.34],[-.68,-.12,-.18,.02],[.05,-.18,.6,-.02],[-.62,.22,-.12,.36],[.08,.2,.64,.38],[-.4,.5,-.08,.65],[.12,.48,.42,.62]];for(const p of paths){ctx.beginPath();ctx.moveTo(cx+side*p[0]*rx,cy+p[1]*ry);ctx.bezierCurveTo(cx+side*p[0]*rx,cy+(p[1]-.12)*ry,cx+side*p[2]*rx,cy+(p[3]-.12)*ry,cx+side*p[2]*rx,cy+p[3]*ry);ctx.bezierCurveTo(cx+side*p[2]*rx,cy+(p[3]+.1)*ry,cx+side*p[0]*rx,cy+(p[1]+.1)*ry,cx+side*p[0]*rx,cy+p[1]*ry);ctx.stroke()}}
function drawBrain(){const w=canvas.clientWidth,h=canvas.clientHeight;ctx.clearRect(0,0,w,h);const cx=w/2,cy=h*.46,rx=Math.min(w*.36,360),ry=Math.min(h*.34,250);pulse*=.985;const energy=Math.max(voiceLevel,pulse);const glow=ctx.createRadialGradient(cx,cy,10,cx,cy,Math.max(rx,ry)*1.8);glow.addColorStop(0,`rgba(139,92,246,${.28+energy*.22})`);glow.addColorStop(.45,'rgba(34,211,238,.09)');glow.addColorStop(1,'rgba(0,0,0,0)');ctx.fillStyle=glow;ctx.fillRect(0,0,w,h);ctx.save();ctx.shadowBlur=28+energy*35;ctx.shadowColor=energy>.1?'#22d3ee':'#8b5cf6';ctx.fillStyle='rgba(12,15,29,.97)';brainPath(cx,cy,rx,ry);ctx.fill();ctx.shadowBlur=0;ctx.strokeStyle=`rgba(34,211,238,${.75+energy*.2})`;ctx.lineWidth=3;brainPath(cx,cy,rx,ry);ctx.stroke();ctx.restore();ctx.save();ctx.strokeStyle=`rgba(196,181,253,${.65+energy*.25})`;ctx.lineWidth=3;ctx.shadowBlur=8;ctx.shadowColor='#8b5cf6';drawGyrus(cx,cy,rx,ry,-1);drawGyrus(cx,cy,rx,ry,1);ctx.shadowBlur=0;ctx.beginPath();ctx.moveTo(cx,cy-ry*.86);ctx.bezierCurveTo(cx-rx*.08,cy-ry*.3,cx+rx*.08,cy+ry*.12,cx,cy+ry*.78);ctx.stroke();ctx.restore();for(let i=0;i<18;i++){const a=i/18*Math.PI*2+performance.now()/3500;const x=cx+Math.cos(a)*rx*(.72+.08*Math.sin(i));const y=cy+Math.sin(a)*ry*(.72+.08*Math.cos(i));ctx.beginPath();ctx.fillStyle=`rgba(34,211,238,${.35+energy*.5})`;ctx.shadowBlur=10;ctx.shadowColor='#22d3ee';ctx.arc(x,y,2.5+energy*3,0,Math.PI*2);ctx.fill()}ctx.shadowBlur=0;requestAnimationFrame(drawBrain)}
resize();addEventListener('resize',resize);drawBrain();send.onclick=()=>ask(message.value);voice.onclick=startVoice;message.oninput=()=>{message.style.height='48px';message.style.height=`${Math.min(message.scrollHeight,180)}px`};message.onkeydown=e=>{if(e.key==='Enter'&&!e.shiftKey){e.preventDefault();ask(message.value)}};document.querySelectorAll('[data-prompt]').forEach(b=>b.onclick=()=>ask(b.dataset.prompt||''));newChat.onclick=()=>{speechSynthesis?.cancel();history=[];location.reload()};
